---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/eliseova/public_html/
    - export REPOSITORIES=/home4/eliseova/repositories/eliseovazquezm/
    - /bin/rsync -av $REPOSITORIES $DEPLOYPATH